### PR TITLE
This PR improves mainly styles

### PR DESCRIPTION
**Pull request by s**
- Changes README.md to README.rst because of PyPI [doesn't support](http://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work) markdown.
- Renames dbConnect.py to dbconnect.py to make it compatible with PEP8. You can consider naming your module name to be all lowercase.
- And some formatting in setup.py

### CODE REVIEW

**Comment by mastizada** [comment]
Thanks for pull request. Sorry, for late response, I'm away due to "Akademik Bilisim" conference.

Yes, naming package dbConnect was mistake, it should be dbconnect, but I'm not sure if its correct time to rename it now.

Also changing md to rst is problem as PIL is not installed in Github and main purpose of README was for Github. We have static html doc in readthedocs and pypi.

If you can cancel README.rst in pull request (remove commit, may be using rebase) I'll be able to merge pr.

**Comment by s** [comment]
No problems! But I didn't quite catch that. The README.rst file will still be readable on [Github](https://github.com/s/dbConnect/blob/master/README.rst) if that's the case. If docs badge is bothering you, I fixed it and can commit it.

**Comment by mastizada** [comment]
Yes, but badges are not working in rst files, as github caches images and then serving them as static files. We have two options here: 1. removing badge and not using them at all (I wanted to add coverage and unit test badges later) 2. Stay in markdown format.

**Comment by s** [comment]
Currently, with my latest commit it should be as how you want. Moreover, you can see [here](https://github.com/s/preprocessor/) that I have a README in rst format and I'm available to add badges. BTW you can preview rst files in your local with [restview](https://pypi.python.org/pypi/restview).

**Comment by mastizada** [comment]
Ok, not sure about github's update frequency but lets use rst. Can you set target to "http://dbconnect.readthedocs.org/?badge=latest" and alt to "Documentation Status"

**Comment by s** [comment]
Done 🎉

**Comment by mastizada** [comment]
Thank you very much. Will update pypi package in next version (after adding missing functionalities).

**Comment by s** [comment]
No problem, I'm planning to help you further. BTW I just forgot a small change and will add it with another PR.

**Pull request merged**
